BOARD_TAG    = nano
BOARD_SUB    = atmega328

#ARDUINO_LIBS = LiquidCrystal
ARDUINO_LIBS = StepperDriver Switch

ARDMK_DIR:=$(PWD)/Arduino-Makefile

ARDUINO_DIR := $(HOME)/arduino/arduino-1.8.2
USER_LIB_PATH := $(PWD)

include $(ARDMK_DIR)/Arduino.mk
